substitutions:
  name: esphome-web-9942fc
  friendly_name: PetsafeFeeder
  device_description: "Petsafe Feeder"
  default_scoops: "1"
  min_scoops: "0"
  max_scoops: "6"
  name_add_mac_suffix: "false"
  min_version: "2025.5.0"

esphome:
  name: $name
  friendly_name: $friendly_name
  min_version: $min_version
  name_add_mac_suffix: $name_add_mac_suffix
  comment: $device_description
  #on_boot:
  #  - light.turn_on:
  #      id: led
  #      effect: fast_blink  
  
esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Disable logging
logger:
  level: INFO
  baud_rate: 0
  
# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  platform: esphome

# Set these in your secrets file.
wifi:
  ap:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

captive_portal: