substitutions:
  name: esphome-web-9942fc
  friendly_name: PetsafeFeeder
  device_description: "Petsafe Feeder"
  default_scoops: "1"
  min_scoops: "0"
  max_scoops: "6"
  name_add_mac_suffix: "false"
  min_version: "2025.5.0"
  rgb_red_pin: "GPIO4"
  rgb_green_pin: "GPIO5"
  rgb_blue_pin: "GPIO18"

esphome:
  name: $name
  friendly_name: $friendly_name
  min_version: $min_version
  name_add_mac_suffix: $name_add_mac_suffix
  comment: $device_description
  on_boot:
    - light.turn_on:
        id: rgbled
        effect: fast_blink_redgreen  
  
esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Disable logging
logger:
  level: INFO
  baud_rate: 0
  
# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  platform: esphome

# Set these in your secrets file.
wifi:
  ap:
    ssid: !secret wifi_ssid
    password: !secret wifi_password
  on_connect:
    - light.turn_on:
        id: rgbled
        effect: slow_blink_blue

captive_portal:

light:
  - platform: rgb
    id: rgbled
    name: "Petsmart Light"
    red: rgb_red_component
    green: rgb_green_component
    blue: rgb_blue_component
    internal: False
    effects:
      - strobe:
          name: fast_blink_redgreen
          colors:
            - state: True
              red: 100%
              green: 0%
              blue: 0%
              duration: 125ms
            - state: True
              red: 0%
              green: 100%
              blue: 0%
              duration: 125ms
      - strobe:
          name: slow_blink_blue
          colors:
            - state: True
              red: 0%
              green: 0%
              blue: 100%
              duration: 250ms
            - state: False
              duration: 750ms

output:
  - platform: ledc
    id: rgb_red_component
    pin: $rgb_red_pin
    inverted: True
  - platform: ledc
    id: rgb_green_component
    pin: $rgb_green_pin
    inverted: True
  - platform: ledc
    id: rgb_blue_component
    pin: $rgb_blue_pin
    inverted: True